---
title: FAQ
---


#### What if there is a file in my local repository that I don’t want in the remote repository?
Great question!  To avoid pushing that file to the remote repository, you can simply avoid staging it for commit.  If it bothers you to see it as an unstaged code change, you can also create a file called `.gitignore`in the repository.  Inside the file, you can simply add the names of the file(s), folder(s), or file extension types (i.e. `*.log`) that you wish for Git to ignore.

#### What if I don’t have anyone who can review my code or pull request?
We talked about the goodness of code review in the “More Advanced” section above.  If you don’t have anyone working on a project with you who is available to review your code, feel free to reach out to <TODO: figure out if this is something we can support>

#### What types of files can I store in my repository?
Any filetype will “work” with version control, in that you can add them to the repository. However, one of the biggest perks of version control is the ability to see specific changes to files. That feature will only work for filetypes that are plain text.  For example, any plain code file will work perfectly, as will .csv and .txt files.  However, there are some file formats that are not stored in plain text format, including:
* Any Microsoft office format (.docx, .xlsx, .pptx, etc)
* Jupyter notebooks, MATLAB notebooks (.ipynb, .mlx)
It is also not advisable to store large data files in git.  For storing large files, see the [Storage Options section](../data-management/storage-options.qmd)
