---
title: Setup
---

## Make a GitHub Account

Before using GitHub, it is necessary to have a Github account.  To make an account, go to the [GitHub website](https://github.com/) and click __Sign Up__, following the prompts to create your account.  As part of the process you will need to verify your email address.  Note that GitHub accounts are associated with people, along the lines of a LinkedIn account, and it may be helpful to have a single personal GitHub account even if you plan to use it outside of your work at RFF.  It is simple to associate multiple email addresses with your account later on, so it is unimportant which email address you create the account with.

## Git Installation

It is necessary to install git onto any computer that you may wish to interact with local repositories.  There are many ways to interact with git, including several applications with graphical user interfaces, which may help to visualize what is happening.  Normally, IT has installed Git on RFF computers. If not, please send a request to [IThelp@rff.org](mailto:ithelp@rff.org) to request a git install.

## Choose a User Interface
When you install git, it generally will already install a couple of applications you can use to interface with git.

1. __Git Bash/CMD__ – This is just like a command prompt for windows, where you enter text-based commands for git.  This is the industry standard, so it is what we suggest for new git users.  Git Bash allows for git commands in addition to standard UNIX commands, whereas Git CMD allows for git commands in addition to standard windows CMD prompt commands.
2. __Git GUI__ – This is a minimalist graphical user interface letting you use git without having to use a command line.  It also allows for simplistic visualization of branches.

If you wish to learn a different user interface, check out the list [here](https://git-scm.com/downloads/guis?os=windows), and check with the IT team before installing.  Most of the concepts will be fairly similar to what we share in the guide.

## Cloning Your First Repository

Say there is an existing repository on GitHub that you would like to download and modify.  The process for creating a local copy on your computer is called [cloning](./terminology.qmd#clone).

1. Open Git Bash or CMD. Navigate to the folder you would like to clone the repository into.  For example `cd repos`.
2. In a browser, navigate to the repository's GitHub page.  For example, https://github.com/e4st-dev/E4ST.jl.
3. Click the button labeled `< > Code`, then copy the URL to clipboard by clicking the logo with intersecting squares.
4. In the Git bash window, type `git clone ` then paste in the repository URL from your clipboard by right-clicking.  Altogether this would look like:
  ```
  git clone https://github.com/e4st-dev/E4ST.jl.git
  ```

## Optional: Set up SSH Keys

If you will be using Git with private repositories, it is worth setting up a key on your PC so that you can freely pull and push from a remote repository without having to enter your password each time.
Follow [these instructions](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) for setting up an SSH key, and [these instructions](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account#adding-a-new-ssh-key-to-your-account) for adding it to your Github account.

There is a small configuration change we need in order to enable the SSH protocol to work with RFF IT systems.  From a git bash window, run the following lines:

* `touch ~/.ssh/config` - This command creates a new empty file in your user home `directory/.ssh` directory.
* `printf "Host github.com\n  Hostname ssh.github.com\n  Port 443" >> ~/.ssh/config` - This command writes 3 line to the newly created config file.  If you were to open the file in a text editor, it would look like:

```
Host github.com
  Hostname ssh.github.com
  Port 443
```

Once you have that set up, when you clone a repository, when copying the URL for the repository, simply select "SSH" before copying the URL.
We’ll go into that in greater detail later.
